In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [1]:
import sys
print(sys.executable)
print(sys.version)

d:\FYP_Coastal_Erosion\.venv\Scripts\python.exe
3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]

In [3]:
df = pd.read_csv("../data/terengganu_coastal_erosion_dataset.csv")

df.head()

,Transect_ID,Coastal_Cell,District,Nearest_JPS_Location,Latitude_DD,Longitude_DD,Annual_Erosion_Rate_m_yr,Distance_to_Infrastructure_m,Economic_Exposure_Score,Physical_Erosion_Score,Total_Risk_Score,ISMP_Risk_Category,Risk_Label
0,TR-00001,C1,Besut,North of Kampung Teluk Budu,5.838528,102.546611,4.951,178.2,3.400,5.000,17.000,1,Critical Risk
1,TR-00002,C1,Besut,North of Kampung Teluk Budu,5.838462,102.546779,4.813,170.4,3.397,4.907,16.670,1,Critical Risk
2,TR-00003,C1,Besut,North of Kampung Teluk Budu,5.838395,102.546947,4.783,223.6,3.394,4.813,16.335,1,Critical Risk
3,TR-00004,C1,Besut,North of Kampung Teluk Budu,5.838329,102.547115,4.695,192.4,3.391,4.718,15.996,1,Critical Risk
4,TR-00005,C1,Besut,North of Kampung Teluk Budu,5.838262,102.547283,4.499,152.4,3.387,4.621,15.654,1,Critical Risk

In [4]:
df.shape

(11371, 13)

In [5]:
df.columns.tolist()

['Transect_ID',
 'Coastal_Cell',
 'District',
 'Nearest_JPS_Location',
 'Latitude_DD',
 'Longitude_DD',
 'Annual_Erosion_Rate_m_yr',
 'Distance_to_Infrastructure_m',
 'Economic_Exposure_Score',
 'Physical_Erosion_Score',
 'Total_Risk_Score',
 'ISMP_Risk_Category',
 'Risk_Label']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11371 entries, 0 to 11370
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Transect_ID                   11371 non-null  str
 1   Coastal_Cell                  11371 non-null  str
 2   District                      11371 non-null  str
 3   Nearest_JPS_Location          11371 non-null  str
 4   Latitude_DD                   11371 non-null  float64
 5   Longitude_DD                  11371 non-null  float64
 6   Annual_Erosion_Rate_m_yr      11371 non-null  float64
 7   Distance_to_Infrastructure_m  11371 non-null  float64
 8   Economic_Exposure_Score       11371 non-null  float64
 9   Physical_Erosion_Score        11371 non-null  float64
 10  Total_Risk_Score              11371 non-null  float64
 11  ISMP_Risk_Category            11371 non-null  int64
 12  Risk_Label                    11371 non-null  str
dtypes: float64(7), int64(1), str(5)
memory usage: 1.1 MB

In [7]:
df.isnull().sum()

Transect_ID                     0
Coastal_Cell                    0
District                        0
Nearest_JPS_Location            0
Latitude_DD                     0
Longitude_DD                    0
Annual_Erosion_Rate_m_yr        0
Distance_to_Infrastructure_m    0
Economic_Exposure_Score         0
Physical_Erosion_Score          0
Total_Risk_Score                0
ISMP_Risk_Category              0
Risk_Label                      0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df["Transect_ID"].duplicated().sum()

np.int64(0)

In [11]:
df["Risk_Label"].value_counts()

Risk_Label
Stable / Acceptable      4826
Warning / Significant    3449
Critical Risk            3096
Name: count, dtype: int64

In [12]:
df["Coastal_Cell"].value_counts().sort_index()

Coastal_Cell
C1      627
C10    1100
C11     990
C12     618
C2     1399
C3      906
C4     1134
C5      314
C6      483
C7      308
C8     2720
C9      772
Name: count, dtype: int64

In [13]:
df.describe()

,Latitude_DD,Longitude_DD,Annual_Erosion_Rate_m_yr,Distance_to_Infrastructure_m,Economic_Exposure_Score,Physical_Erosion_Score,Total_Risk_Score,ISMP_Risk_Category
count,11371.000000,11371.000000,11371.000000,11371.000000,11371.000000,11371.000000,11371.000000,11371.000000
mean,5.095691,103.172347,2.140549,379.687881,1.870774,2.172132,3.747068,2.152141
std,0.477066,0.287658,1.906429,109.059221,0.869950,1.546518,3.259276,0.820729
min,4.211250,102.546611,0.000000,25.800000,1.000000,0.000000,0.000000,1.000000
25%,4.697556,102.949749,0.634000,316.750000,1.038000,0.656000,0.969500,1.000000
50%,5.130093,103.251289,1.848000,399.500000,1.630000,2.000000,3.424000,2.000000
75%,5.529656,103.441587,3.120500,466.400000,2.500000,3.477000,5.485500,3.000000
max,5.838528,103.484212,10.537000,578.300000,4.000000,5.000000,17.000000,3.000000

In [14]:
df["Coastal_Cell"].value_counts().sort_index()

Coastal_Cell
C1      627
C10    1100
C11     990
C12     618
C2     1399
C3      906
C4     1134
C5      314
C6      483
C7      308
C8     2720
C9      772
Name: count, dtype: int64

In [15]:
df.groupby("Coastal_Cell")["Annual_Erosion_Rate_m_yr"].agg(
    ["count", "mean", "min", "max"]
).round(3)

              count   mean    min     max
Coastal_Cell
C1              627  1.484  0.000   4.951
C10            1100  1.529  0.000   8.294
C11             990  1.377  0.000   3.095
C12             618  3.787  1.981  10.537
C2             1399  3.135  1.643   4.341
C3              906  1.138  0.500   2.353
C4             1134  3.396  0.000  10.255
C5              314  0.062  0.000   0.150
C6              483  1.362  0.000   3.573
C7              308  1.913  0.127   3.017
C8             2720  2.398  0.076   4.059
C9              772  1.252  0.000   3.770