In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    "../data/processed/terengganu_coastal_erosion_transects_144.csv"
)

In [3]:
print("Dataset shape:", df.shape)

print("\nSource distribution:")
print(df["Source_Type"].value_counts())

print("\nProtected points:", df["Is_Protected"].sum())

print("\nDataset preview:")
display(df.head())

Dataset shape: (2775, 29)

Source distribution:
Source_Type
Interpolated    2631
JPS_Original     144
Name: count, dtype: int64

Protected points: 9

Dataset preview:

,No,Coastal_Cell,District,Area_Location,Longitude_DMS,Latitude_DMS,Longitude_DD,Latitude_DD,Annual_Erosion_Rate_m_yr,Physical_Erosion_Score,...,Previous_No,Start_New_Segment,Segment_ID,Source_Type,Start_JPS_No,End_JPS_No,Nearest_JPS_No,Distance_From_Start_m,Fraction_Between_Stations,Transect_ID
0,1.0,C1,Besut,North of Kampung Teluk Budu,"102°32'47.8""E","5°50'18.7""N",102.546611,5.838528,4.9400,5.0000,...,NaN,True,1,JPS_Original,1,1,1,0.0,0.000000,1
1,NaN,C1,Besut,North of Kampung Teluk Budu,NaN,NaN,102.546779,5.838462,4.8632,4.9223,...,NaN,NaN,1,Interpolated,1,2,1,20.0,0.015542,2
2,NaN,C1,Besut,North of Kampung Teluk Budu,NaN,NaN,102.546947,5.838395,4.7864,4.8446,...,NaN,NaN,1,Interpolated,1,2,1,40.0,0.031084,3
3,NaN,C1,Besut,North of Kampung Teluk Budu,NaN,NaN,102.547115,5.838329,4.7097,4.7669,...,NaN,NaN,1,Interpolated,1,2,1,60.0,0.046626,4
4,NaN,C1,Besut,North of Kampung Teluk Budu,NaN,NaN,102.547283,5.838262,4.6329,4.6892,...,NaN,NaN,1,Interpolated,1,2,1,80.0,0.062168,5

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11370 entries, 0 to 11369
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Transect_ID               11370 non-null  str
 1   Distance_Along_Coast_m    11370 non-null  float64
 2   Latitude_DD               11370 non-null  float64
 3   Longitude_DD              11370 non-null  float64
 4   Source_Start_No           11370 non-null  int64
 5   Source_End_No             11370 non-null  int64
 6   Nearest_Source_Index      11370 non-null  int64
 7   Nearest_JPS_No            11370 non-null  int64
 8   Coastal_Cell              11370 non-null  str
 9   District                  11370 non-null  str
 10  Nearest_JPS_Location      11370 non-null  str
 11  NCES_2015_Category        11370 non-null  int64
 12  Is_Protected              11370 non-null  int64
 13  Annual_Erosion_Rate_m_yr  10296 non-null  float64
 14  Physical_Erosion_Score    10296 non-null  float64
 15  Economic_Score            11370 non-null  float64
 16  Total_Risk_Score          11370 non-null  float64
dtypes: float64(7), int64(6), str(4)
memory usage: 1.5 MB

In [5]:
df.dtypes

Transect_ID                     str
Distance_Along_Coast_m      float64
Latitude_DD                 float64
Longitude_DD                float64
Source_Start_No               int64
Source_End_No                 int64
Nearest_Source_Index          int64
Nearest_JPS_No                int64
Coastal_Cell                    str
District                        str
Nearest_JPS_Location            str
NCES_2015_Category            int64
Is_Protected                  int64
Annual_Erosion_Rate_m_yr    float64
Physical_Erosion_Score      float64
Economic_Score              float64
Total_Risk_Score            float64
dtype: object

In [6]:
print(df.isnull().sum())

Transect_ID                    0
Distance_Along_Coast_m         0
Latitude_DD                    0
Longitude_DD                   0
Source_Start_No                0
Source_End_No                  0
Nearest_Source_Index           0
Nearest_JPS_No                 0
Coastal_Cell                   0
District                       0
Nearest_JPS_Location           0
NCES_2015_Category             0
Is_Protected                   0
Annual_Erosion_Rate_m_yr    1074
Physical_Erosion_Score      1074
Economic_Score                 0
Total_Risk_Score               0
dtype: int64

In [7]:
missing_erosion = df[
    df["Annual_Erosion_Rate_m_yr"].isna()
]

print("Rows with missing erosion:", len(missing_erosion))

print(
    "\nProtection status of missing erosion rows:"
)

print(
    missing_erosion["Is_Protected"].value_counts()
)

Rows with missing erosion: 1074

Protection status of missing erosion rows:
Is_Protected
1    1074
Name: count, dtype: int64

In [8]:
print(
    "Duplicate rows:",
    df.duplicated().sum()
)

print(
    "Duplicate Transect IDs:",
    df["Transect_ID"].duplicated().sum()
)

print(
    "Duplicate coordinates:",
    df.duplicated(
        subset=["Latitude_DD", "Longitude_DD"]
    ).sum()
)

Duplicate rows: 0
Duplicate Transect IDs: 0
Duplicate coordinates: 0

In [9]:
print(
    "Latitude:",
    df["Latitude_DD"].min(),
    "to",
    df["Latitude_DD"].max()
)

print(
    "Longitude:",
    df["Longitude_DD"].min(),
    "to",
    df["Longitude_DD"].max()
)

Latitude: 4.211354251935916 to 5.838528
Longitude: 102.546611 to 103.48421152585402

In [10]:
df[
    [
        "Annual_Erosion_Rate_m_yr",
        "Physical_Erosion_Score",
        "Economic_Score",
        "Total_Risk_Score"
    ]
].describe()

,Annual_Erosion_Rate_m_yr,Physical_Erosion_Score,Economic_Score,Total_Risk_Score
count,10296.000000,10296.000000,11370.000000,11370.000000
mean,2.371010,2.405607,1.870727,3.758587
std,1.902651,1.470711,0.869975,3.334255
min,0.000000,0.000000,1.000000,0.000000
25%,0.891402,1.045539,1.037549,0.889793
50%,2.112563,2.274563,1.629371,3.355062
75%,3.344570,3.813266,2.500000,5.519308
max,10.530535,5.000000,4.000000,17.000000

In [11]:
df["Coastal_Cell"].value_counts().sort_index()

Coastal_Cell
C1      627
C10    1100
C11     990
C12     617
C2     1399
C3      906
C4     1134
C5      314
C6      483
C7      308
C8     2720
C9      772
Name: count, dtype: int64

In [12]:
print(
    "Number of coastal cells:",
    df["Coastal_Cell"].nunique()
)

Number of coastal cells: 12

In [13]:
print(
    "Number of districts:",
    df["District"].nunique()
)

df["District"].value_counts()

Number of districts: 6

District
Setiu               3439
Kemaman             2313
Marang              2171
Dungun              1960
Kuala Terengganu     860
Besut                627
Name: count, dtype: int64

In [14]:
protection_counts = df["Is_Protected"].value_counts()

print(protection_counts)

print(
    "\nProtected percentage:",
    round(
        df["Is_Protected"].mean() * 100,
        2
    ),
    "%"
)

Is_Protected
0    10296
1     1074
Name: count, dtype: int64

Protected percentage: 9.45 %

In [15]:
print("=== FINAL PROCESSED DATASET CHECK ===")

print("Rows:", len(df))
print("Columns:", len(df.columns))

print(
    "Unique Transect IDs:",
    df["Transect_ID"].nunique()
)

print(
    "Coastal cells:",
    df["Coastal_Cell"].nunique()
)

print(
    "Districts:",
    df["District"].nunique()
)

print(
    "Protected points:",
    df["Is_Protected"].sum()
)

print(
    "Duplicate rows:",
    df.duplicated().sum()
)

=== FINAL PROCESSED DATASET CHECK ===
Rows: 11370
Columns: 17
Unique Transect IDs: 11370
Coastal cells: 12
Districts: 6
Protected points: 1074
Duplicate rows: 0

In [4]:
# Step 2: Check dataset quality

features = [
    "Annual_Erosion_Rate_m_yr",
    "Physical_Erosion_Score",
    "Economic_Score"
]

print("=== DATA QUALITY CHECK ===")

print("Total points:", len(df))

print("\nDuplicate Transect IDs:")
print(df["Transect_ID"].duplicated().sum())

print("\nMissing coordinates:")
print(df[
    ["Latitude_DD", "Longitude_DD"]
].isnull().sum())

print("\nMissing AI features (non-protected only):")
print(
    df.loc[df["Is_Protected"] == 0, features]
    .isnull().sum()
)

print("\nOriginal JPS station numbers:")
print(
    df.loc[df["Source_Type"] == "JPS_Original", "No"]
    .nunique()
)

=== DATA QUALITY CHECK ===
Total points: 2775

Duplicate Transect IDs:
0

Missing coordinates:
Latitude_DD     0
Longitude_DD    0
dtype: int64

Missing AI features (non-protected only):
Annual_Erosion_Rate_m_yr    0
Physical_Erosion_Score      0
Economic_Score              0
dtype: int64

Original JPS station numbers:
144

In [5]:
# Step 3: Check erosion data ranges

df_valid = df[df["Is_Protected"] == 0]

print("=== EROSION DATA SUMMARY ===")

print(df_valid[
    ["Annual_Erosion_Rate_m_yr",
     "Physical_Erosion_Score",
     "Economic_Score"]
].describe().round(2))

print("\nNegative erosion rates:",
      (df_valid["Annual_Erosion_Rate_m_yr"] < 0).sum())

print("\nMaximum erosion rate:",
      df_valid["Annual_Erosion_Rate_m_yr"].max())

print("\nNon-protected points:", len(df_valid))
print("Protected points:", df["Is_Protected"].sum())

=== EROSION DATA SUMMARY ===
       Annual_Erosion_Rate_m_yr  Physical_Erosion_Score  Economic_Score
count                   2766.00                 2766.00         2766.00
mean                       3.08                    2.63            1.90
std                        2.77                    1.41            0.84
min                        0.00                    0.00            1.00
25%                        1.24                    1.55            1.10
50%                        2.27                    2.70            1.58
75%                        3.30                    3.57            2.60
max                       15.52                    5.00            4.00

Negative erosion rates: 0

Maximum erosion rate: 15.52

Non-protected points: 2766
Protected points: 9